### ISSUE TITLE
Display a comment for UD

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#315]
Initially written by @Sylvain303 at https://github.com/ucoin-io/ucoin/issues/280

---

We talked about this during @Insoleet conference: this "Comment" field must either:
- disappear, because `Comment` field in uCoin protocol is a purely technical comment (not a human one)
- stay, but it must be filled in by the local user himself. Maybe for UD this could be automated by Sakia

**Comment by Sylvain303** [comment]
The UD are not "created" by ucoin nodes?

**Comment by Insoleet** [comment]
Actually they are "authorized to be sent to other people" by ucoin nodes !

**Comment by Sylvain303** [comment]
Hum, may be. So the UD are really generated by ucoin's node. So it's the node which generates the transaction which is holding the DU, right? So the comment have to be produced by the node?

Sakia is the wallet, it displays the information, and doesn't produce it, right?

**Comment by Insoleet** [comment]
No it's a bit more complicated.

Transactions are made of source of money ( My current sources : http://metab.ucoin.io/tx/sources/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU )
A source can have two origins : a dividend, or a transaction.

If you issued a dividend, it creates a source that you can spend. In the example, the source is formatted in json. The fingerprint is the hash of the block ( @c-geek you should considered renaming this to hash, it's old, from OpenUDC/first uCoin days !). The number is the number of the block.
```json
    "pubkey": "8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU",
    "type": "D",
    "number": ​45508,
    "fingerprint": "0000DCBE0A640D70D6EB86FB795988EC3CAA1198",
    "amount": ​2739899613848797
```
If you receive a transaction, the outputs of the transactions you are the recipient of will be a source that you can spend. In the example, the fingerprint is the hash of the transaction. The number is the block number the transaction was written in. ( @c-geek : actually, shouldn't you add the block hash here because of multibranch ? )
```json
{

    "pubkey": "8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU",
    "type": "T",
    "number": ​43916,
    "fingerprint": "486565FE5FB114ECAFEF5489A0DAA6B09BC0321F",
    "amount": ​7612152705262
},
```

The wallet responsibility when a user sends money is to takes available sources, put them in a Transaction document, signed by the sender. It also creates outputs generated from these sources, aka inputs. Total of ouputs = total of inputs. The wallet broadcast this document to the nodes.

The nodes responsibility is too make sure the inputs of the transactions are available and owned by the user at the origin of the transaction. The transaction is then considered valid and included in next block computed by the node.
