### ISSUE TITLE
Not Member in the WoT, but member in the list...

### ISSUE THREAD

**Issue by vtexier** [duniter/sakia#379]
Kimamila is not a Member in the WoT, but  a member in the identity list...

Not a member for ucoin here :  http://metab.ucoin.io:9201/wot/certifiers-of/kimamila

(despite all certifications and membership ok... is the bug here ?)

It is well reflected in WoT, but not in the member list where Kimamila is a member...

[edit]
identity list use membership validity, so it reflect ucoin info ok. I think there's is a mistake in the isMember property of ucoin.

**Comment by Insoleet** [comment]
What is your opinion about it @c-geek ?

**Comment by c-geek** [comment]
There is no bug at all, neither in Sakia nor uCoin, but maybe we lack some informations to understand.

If you look at certifiers-of URI, you can see that only 2 of the certifications are actually written (`written` field is `null` for 2 of the 4 certs).

So kimamila [is not a member](http://twiced.fr:9201/wot/members), because he was automatically [excluded 10 days ago](http://metab.ucoin.io/blockchain/block/49920) because he lacked certifications (since he has a valid membership, it is the only remaining reason for automatic exclusion).

Since kimamila is no more a member, its new certifications can be written only if he renews again. Then we will see him as a member and its 3 or 4 certifications will all be written.

So maybe we would need in Sakia a different looking for certifications not written yet, so we understand something is going on.

But if we wanted to go further and display the reasons why a member has a given state, then maybe:

* uCoin could give more informations in [http://metab.ucoin.io/wot/requirements/kimamila](http://metab.ucoin.io/wot/requirements/kimamila) URI, like the current state of the identity that could include:
    * `excluded: 49220` to understand the member was kicked at this block
* clients like Sakia could deduce (yes, deduce, without explicital informations ... I know you might prefer explicit) that the member was kicked because of either:
    * lacking renewal (regarding the membership expiracy date)
    * missing, at some time, of enough certifications

**Comment by vtexier** [comment]
@c-geek : ok i was missing this important point that a kicked member need to renew, even if his membership was valid.

So what informations need Sakia to alert the user that his last renew is useless ?

* Status member is false.
* Enough valid certifications (counting not written ones).

We have all those informations in `wot/certifiersOf` allready I think...

But for a clear status in Sakia, the identity list should show : 

* Member color status in the first two columns (uid/pubkey)
* Membership renewal color status in the two next columns (renew/expire date)

**Comment by vtexier** [comment]
In fact, the problem here is : 

* Every "membership renewal" BEFORE the "membership exclusion" are no more valid.

So `wot/requirements/kimamila` should not return a expiration date for the membership... Because this
membership has ENDED.

* "membershipExpiresIn": ​1346779

should be 0. So Sakia will know the identity needs renewal...

**Comment by c-geek** [comment]
Yes this makes sense.

**Comment by Insoleet** [comment]
I implemented the requirements url but I'm not sure to understand what has to be done about the issue found by vit. Could you do some short version out of it please ?

**Comment by vtexier** [comment]
To make it short, every time we need to display membership status, the valid information is in the requirements field 

> membershipExpiresIn

Date=member,0=not a member

**Comment by c-geek** [comment]
Fixed in duniter/duniter#352. In next release, `membershipExpiresIn` will have value `0` if the member has been kicked.
