### ISSUE TITLE
Implicit revocation

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#386]
Original change in https://github.com/ucoin-io/ucoin/issues/336

-----

Now, an identity which does not renew is considered *excluded*. But if it does not join again after twice the delay of a membership validity, it is considered *revoked* and won't be able to join again anymore.

**Comment by c-geek** [comment]
I mean twice the delay *from* last renew. So once the delay from last exclusion.

**Comment by Insoleet** [comment]
I think of only disabling buttons like "Certifiy" or "Renew" when an identity is revoked. The community tile would show, instead of "Member" or "Non-member" the text "Revoked", in red. I guess Non-member should be Orange in this case.

We need to add a warning in sakia that the identity will be revoked if the member does not renew before *date*.

**Comment by Insoleet** [comment]
Should be done in https://github.com/duniter/sakia/commit/269b83b0bc47f2e8a9dba71f207ac82cd6fc4524
