### ISSUE TITLE
Crash if user identity is not in the network

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#391]
I've created a new currency, super_currency. My user is cgeek, I am alone in this currency and everything is fine.

Now a new user named *tobi* wants to join this currency, creates a new account in Sakia which spreads its identity on the network successfully.

But for some reason this identity has been deleted from the database thereafter, without this identity being written in the blockchain. So, /wot/lookup does not find him anymore.

Whatever document tobi tries to send to the network, Sakia will crash with a similar error:

```
ERROR:<string>:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<send_membership_demand() done, defined at sakia/gui/community_view.py:313> exception=LookupFailureError('AhzznLhY4koKxx7PPZfnwp6N9mvW1D67KJs1YBTfSGpn', <sakia.core.community.Community object at 0x7fc787dd95e8>)>
Traceback (most recent call last):
  File "sakia/core/registry/identity.py", line 119, in selfcert
  File "sakia/core/net/api/bma/access.py", line 240, in future_request
  File "ucoinpy/api/bma/wot.py", line 170, in __get__
  File "ucoinpy/api/bma/api.py", line 165, in requests_get
ValueError: status code != 200 => 404 ({
  "ucode": 2001,
  "message": "No matching identity"
})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
  File "sakia/gui/community_view.py", line 318, in send_membership_demand
  File "sakia/core/account.py", line 471, in send_membership
  File "sakia/core/registry/identity.py", line 147, in selfcert
sakia.tools.exceptions.LookupFailureError: Error : Person looked by AhzznLhY4koKxx7PPZfnwp6N9mvW1D67KJs1YBTfSGpn in <sakia.core.community.Community object at 0x7fc787dd95e8> not found 
```

Even account configuration (which sends the identity again) encounters this bug.

I know this might never happen in reality, because we will find the identity somewhere. But with brand new currencies which can be made for testing purposes, it will crash.

**Comment by Insoleet** [comment]
Well in theory, if the user does not have his identity published, the membership button should not be available. ( https://github.com/ucoin-io/sakia/blob/dev/src/sakia/gui/community_view.py#L296 )

The user should then use the "More" actions > "Publish UID".

I fixed the code to use UcoinErrors instead of HTTP error codes. Maybe this will help a little. 
Also, small question : did you create, remove, create, remove a community with the same name a lot in sakia and ucoin ? Because I figured the caching system didn't like having a community with a given name being removed and added with a new cache at the moment. Kind of buggy...
