### ISSUE TITLE
Error connect 

### ISSUE THREAD

**Issue by liberiumorg** [duniter/sakia#480]
#206

 After clicking "Connect" no windows not only opens an error in the terminal:

Version : 0.20.2
.exe 64bit

`QWindowsWindow :: setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow / 'menu_change_accountWindow'`

![sakia 0 20 2](https://cloud.githubusercontent.com/assets/6820705/16728280/ce387148-4765-11e6-9d34-dce7d657850a.jpg)

**Comment by Insoleet** [comment]
You have to click on "New account" to add your account locally. A window will be opened which will let you choose if you want to register a new account on the network, or use an existing one.

The button `Connect` on the main view is here to switch between accounts added locally. I agree, this could open the window to connect instead of having to go throught "new account"... :+1:
