### ISSUE TITLE
Searching a new identity in WoT tab take to much time

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#487]
Searching a new identity in WoT tab take a long time, like two minutes.
The entire networks seems to be browsed.
Could it be enhanced?

**Comment by Idyllei** [comment]
What method of storage is being used for the identities' information when it is being looked-up?
If you use a hash table, would there be any improvement? 

If the key is the identity's pubkey and the value is an object containing information such as membership history, etc., would it be possible to speed up the search?

**Comment by Insoleet** [comment]
I think this is mostly due to 2 facts : 

- We are currently running a massive load of requests to find a given identity. This is because, one year ago, Duniter APIs were not as complete as nowaday. This should be enhanced.
- When we are looking for the path between us and another one, we have to parse the WoT. It can take much time before being sure that there is no path between us and someone else.
