### ISSUE TITLE
Monetary Mass (UD) is not correct

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#495]
Given the fact we have 119 members, and c = 10%, we can't have more than 1190 UD as monetary mass.

![image](https://cloud.githubusercontent.com/assets/969136/17462467/5e41668e-5cae-11e6-8978-0d3693b26e28.png)

**Comment by c-geek** [comment]
If the problem is that you need to have 1 UD displayed in the transactions as below:

![image](https://cloud.githubusercontent.com/assets/969136/17462487/e01b706e-5cae-11e6-957e-da3a37260b41.png)

then the solution would be to have UD(t+1) displayed like a pending transaction, but with value = UD(t+1). So the monetary mass could be 1190 UD.

cc @vtexier

**Comment by vtexier** [comment]
The monetary mass is correct as explain in the informations tab. UD (t) is used, because with the actual formula of the UD, UD (t+1) can not be known as N (t+1) is unknown.
So as @galuel said, we can not use N (t+1) as we do not known it.

What I suggest is, when Duniter will use the UDB formula, where N is no more involved, to use UDB (t+1).
May be we should discuss this on the forum to display expected and accurate numbers in all Duniter apps.

**Comment by Insoleet** [comment]
With the UDG formula, where are we going with this issue ?

**Comment by galuel** [comment]
Just choose last known DU(t), M(t+1) (current) and N(t) (last known N used to calculate DU(t+1), and don't use N(current)).

And so you will have (1/c +1) DU(t) in M(current), because DU(t) is not DU(current, unknown, calculated by Duniter in next t+1).

For a good "dt" (day), it is not a lot in a prod money, with c = 0,027% / day => M/N = 3703 DU, so you will obtain 3704 DU instead, not a big deal...
