### ISSUE TITLE
Sakia 0.30.7 Can't send money

### ISSUE THREAD

**Issue by manolollr** [duniter/sakia#604]
When I do a transaction using Sakia client I must wait many hours before I can do another transaction. But using Cesium I can continue doing transactions.

This is the error tha appears:

![sakia_error](https://cloud.githubusercontent.com/assets/8089376/22935629/6cd89b7a-f2d3-11e6-8ba6-cfb3acd54ffd.png)

And this is the content of http://gtest.duniter.org:10900/tx/sources/4qesC5stf342FJL7w5AQndwc3GmrxA49DdUZcZt4Ti2c

{
"currency": "gtest",
"pubkey": "4qesC5stf342FJL7w5AQndwc3GmrxA49DdUZcZt4Ti2c",
"sources": [
{
"type": "T",
"noffset": 2,
"identifier": "4B7318074EDB8A619D9EB7C169982FE9644C8A2305FE1C993F62C8A33E6FF2D6",
"amount": 3,
"base": 0
},
{
"type": "T",
"noffset": 1,
"identifier": "BC177ECEEB5248E435B9AF9DDA5BF4CE2DD602323E9A1BB0644110894DE74DF4",
"amount": 1016,
"base": 1
},
{
"type": "T",
"noffset": 1,
"identifier": "7CD236EF0C2592CF5B847BEC21C66E841FD071B868F569C9C821291569FF237A",
"amount": 867,
"base": 1
}
]
}

If my calculations are correct I have 3 sources with a total amount of 188.33 Gtest

Here sakia.log: http://pastebin.com/UiFa86eE

And gtest.db:

[gtest.db.tar.gz](https://github.com/duniter/sakia/files/774543/gtest.db.tar.gz)

**Comment by manolollr** [comment]
bohh, today it works.

I will test in an hour and 5 hours to verify if it is still working

**Comment by manolollr** [comment]
At 18:00 it works. I will test at 21:00

**Comment by manolollr** [comment]
Now it has failed. I've tried to send more than 10% of total money and doesn't allow it. Is there a 10% limit? If this is the case it will be better to show a different error message. A message saying you have exceeded the limit.

**Comment by Insoleet** [comment]
After analyzing this, this is because of sources rotation.

Lets take the first case : 

 - You have 3 at base 0, it is 3*10⁰ = 3
 - You have 1016 at base 1, it is 1016x10¹ = 10160
 - You have 867 at base 1, it is 867x10¹ = 8670

 You are trying to send 106. But sakia can't do this because :  
 - With only sources of base 0, you have maximum 3
 - You can send more with sources of base 1, but then the output of the tx needs to be on base 1 (low base pruning rule). In such a case it is impossible to send it.

I made the choice to display base 0 and base 1 amounts on a base 0 display. But I wonder now if it is a good idea : once the first UD are generated on base 1, maybe I should only authorize base 1 transactions...

What do you think, @c-geek , @blavenie ?

**Comment by c-geek** [comment]
> In such a case it is impossible to send it.

Yes you are right, I could send [100 ; 103] but not [104 ; 109]. The latter case would increase the quantity of number in base 0.

I think you should display everything on current base, and only allow current base transactions (with Sakia taking into account sources in base 0, though). So yes, base 1.

It occurs only every 23 years, so it's OK to me.
