### ISSUE TITLE
Identities request take too much time

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#641]
When adding a new identity, identity requesting takes too much time as there is more than hundred identities now on Ğ1:
![capture du 2017-03-15 08-54-51](https://cloud.githubusercontent.com/assets/4758871/23938651/7ac8818c-095d-11e7-964f-c5aea518254f.png)

**Comment by Insoleet** [comment]
This is a choice I made for Sakia to have correct performances using only BMA API. Get as much informations as possible during the initialize loading, and then refresh informations when needed when blockchain gets updated.

The time needed to get informations about a given identity is caused by 3 requests : 
 - Lookup
 - Membership
  - Requirements

It won't be possible to make it faster before we use another API.
