### ISSUE TITLE
On identity creation: urge to save the revocation document on the disk

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#664]
> Ah oui, tu veux dire que Gildas avait accès à son 1er compte que vous avez donc certifié, puis a perdu ses accès et alors il a créé un nouveau compte que vous avez de nouveau certifié, sans qu'il ai pu révoquer le 1er ?

> Si c'est le cas, on voit bien à quel point il devient crucial qu'au moment de la création d'un compte, le logiciel harcèle l'utilisateur pour stocker sa révocation sur son PC (on pourrait même imaginer que tant que cette action n'est pas faite, le logiciel refuse de fonctionner).

In other words: the revocation document is an absolute security: it should have been saved on account creation. Sakia could even refuse to work as long as the revocation document has not been saved.

**Comment by Insoleet** [comment]
For 0.31, a popup will ask the user to save his revocation file right after publishing his identity.

The popup should be present also when the software generates a new identity because the old one expired and the user asked to publish his UID.

For 0.32, the ergonomy feature should help the user with one window to manage all his identity stuff.

**Comment by yann1108** [comment]
Exactly the revocation file should be asked to be downloaded at the account creation.
I advised not to make it optional but an obligation to finish the creation process.
An advisory pop-up is not enough, since that file is a corner stone of the system, you must have it to even have the account.
